OAUTH_CONSUMER_TOKEN: ''
OAUTH_SECRET_TOKEN: ''
SECRET_KEY: ''  # Secret key
DB_HOST: 'localhost'
DB_NAME: 'quarry'
DB_USER: ''
DB_PASSWORD: ''
BROKER_URL: 'redis://'
CELERY_RESULT_BACKEND: 'redis://'
CELERYD_CONCURRENCY: 24  # Since all tasks are IO bound
CELERY_ACKS_LATE: True  # Tasks are idempotent!
CELERY_TRACK_STARTED: True
REPLICA_HOST: '127.0.0.1'
REPLICA_DB: 'enwiki_p'
REPLICA_USER: ''
REPLICA_PASSWORD: ''
REPLICA_PORT: 3309
OUTPUT_PATH_TEMPLATE: '/data/project/quarry/results/%s/%s.json'
REDIS_HOST: '127.0.0.1'
REDIS_PORT: 6379
REDIS_DB: 0
QUERY_TIME_LIMIT: 60  # 1 minute
QUERY_RESULTS_PER_PAGE: 50
KILLER_LOG_PATH: 'killer.log'
